# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2023-05-31 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20230531_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_de_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
